#https://aws.amazon.com/blogs/devops/serverless-ui-testing-using-selenium-aws-lambda-aws-fargate-and-aws-developer-tools/

FROM amazon/aws-lambda-python:3.9

COPY install-browsers.sh /tmp/
RUN yum install xz atk cups-libs gtk3 libXcomposite alsa-lib tar \
    libXcursor libXdamage libXext libXi libXrandr libXScrnSaver \
    libXtst pango at-spi2-atk libXt xorg-x11-server-Xvfb \
    xorg-x11-xauth dbus-glib dbus-glib-devel unzip bzip2 -y -q
RUN chmod +x /tmp/install-browsers.sh
RUN /tmp/install-browsers.sh

ENTRYPOINT ["/bin/bash", "-l", "-c"]

CMD ["chromedriver --version"]